### ISSUE TITLE
cant resolve dependency

### ISSUE THREAD

**Issue by lDionis** [andyb129/BeerProgressView#1]
When i try to set dependency and sync project i get an error:
 "Failed to resolve uk.co.barbuzz.beerprogressview:beerprogressview:0.0.4"
can u help me to fix it?

**Comment by andyb129** [comment]
My mistake, I've added the dependancy incorrectly. The correct one should be - compile 'uk.co.barbuzz:beerprogressview:0.0.4' . I'll update the readme too. Thanks for flagging this.
