### ISSUE TITLE
Typo in Gradle dependency description in README.md

### ISSUE THREAD

**Issue by depodefi** [andyb129/BeerProgressView#4]
Is:
dependencies {
  compile 'uk.co.barbuzz.beerprogressview:0.0.4'
}
Should be:
dependencies {
  compile 'uk.co.barbuzz:beerprogressview:0.0.4'
}

**Comment by andyb129** [comment]
thanks for pointing that mistake out 👍 , I'll correct that tonight.

**Comment by depodefi** [comment]
no problem :) thanks for creating library. it's used in my app
https://play.google.com/store/apps/details?id=mobillnet.com.fanwars
I haven't yet time to put there any info about used libs but will do so
once I will have some more time. Now I got lot of things in the backlog and
really tight schedule. ;)

## 

Best regards,
Michał

**Comment by andyb129** [comment]
Great! glad its been put to good use! :-) a ref to the library would be appreciated.
